[parameter]
[parameter.general]

[parameter.simple_update]
num_step = 200
tau = 0.01

[parameter.full_update]
num_step = 0
tau = 0.01

[parameter.ctm]
iteration_max = 100
dimension = 5  # Note: run.py overwrites this

[lattice]
type = "triangular lattice"
L = 3
W = 3
virtual_dim = 2 # Note: run.py overwrites this
initial = "random"

[model]
type = "boson"
t = 0.1
V = 1.0

[correlation]
r_max = 30
operators = [[0,0]]
