[parameter]
name = "hypercubic"
dim = 2
L = [ 8, 8,]
bc = [ true, true,]
basis = [ [ "1.0", "0.0",], [ "0.0", "1.0",],]

[unitcell]
[[unitcell.sites]]
siteid = 0
type = 0
coord = [ 0.0, 0.0,]

[[unitcell.bonds]]
bondid = 0
type = 0

[unitcell.bonds.source]
siteid = 0
[unitcell.bonds.target]
siteid = 0
offset = [ 1, 0,]
[[unitcell.bonds]]
bondid = 1
type = 0

[unitcell.bonds.source]
siteid = 0
[unitcell.bonds.target]
siteid = 0
offset = [ 0, 1,]
