[parameter]
[parameter.general]

[parameter.simple_update]
num_step = 1000
tau = 0.01

[parameter.full_update]
num_step = 0
tau = 0.01

[parameter.ctm]
iteration_max = 100

[lattice]
type = "square lattice"
L = 2
W = 2
initial = "antiferro"
virtual_dim = 2

[model]
type = "spin"
J = 1.0
