include(CheckCXXCompilerFlag)

macro(cxx11)
  set(ENABLED_CXX11 ON)
  if(${CMAKE_VERSION} VERSION_LESS 3.1.3)
    check_cxx_compiler_flag("-std=c++11" supports_cxx11)
    check_cxx_compiler_flag("-std=c++0x" supports_cxx0x)
    if(supports_cxx11)
      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
    elseif(supports_cxx0x)
      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++0x")
    else()
      message(FATAL "The compiler seems not to support C++11.")
      set(ENABLED_CXX11 OFF)
    endif()
  else()
    set(CMAKE_CXX_STANDARD 11)
    set(CMAKE_CXX_STANDARD_REQUIRED ON)
    set(CMAKE_CXX_EXTENSIONS OFF)
  endif()
endmacro()
