[parameter]
[parameter.general]
is_real = true
tensor_save = "tensor"
[parameter.simple_update]
num_step = 1000
tau = 0.01
[parameter.full_update]
num_step = 0
tau = 0.01
[parameter.ctm]
iteration_max = 10
dimension = 10

[tensor]
type = "square lattice"
L_sub = [2, 2]
skew = 0

[[tensor.unitcell]]
virtual_dim = [2, 2, 2, 2]
index = [0, 3]
physical_dim = 2
initial_state = [1.0, 0.0]
noise = 0.01

[[tensor.unitcell]]
virtual_dim = [2, 2, 2, 2]
index = [1, 2]
physical_dim = 2
initial_state = [0.0, 1.0]
noise = 0.01

[[hamiltonian]]
dim = [2]
sites = [0, 3]
elements = """
0 0 -0.5 0.0
1 1 0.5 0.0
"""

[[hamiltonian]]
dim = [2]
sites = [1, 2]
elements = """
0 0 0.5 0.0
1 1 -0.5 0.0
"""

[observable]
[[observable.onesite]]
name = "Sz"
group = 1
sites = []
dim = 2
elements = """
0 0 0.5 0.0
1 1 -0.5 0.0
"""

[[observable.twosite]]
name = "SzSz"
group = 1
dim = [2, 2]
bonds = """
0 1 0
1 1 0
2 1 0
3 1 0
0 0 1
1 0 1
2 0 1
3 0 1
"""
ops = [1, 1]
