name: Linux

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1,15 * *' # JST 9:00 AM, 1st and 15th of every month


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-22.04", "ubuntu-24.04"]
        python-version: ["3.9"]
        compiler: ["g++-12"]
        include:
          - os: "ubuntu-22.04"
            python-version: "3.9"
            compiler: "g++-9"
          - os: "ubuntu-24.04"
            python-version: "3.9"
            compiler: "g++-14"
          - os: "ubuntu-24.04"
            python-version: "3.13"
            compiler: "g++-12"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: apt
        run: |
          sudo apt update
          sudo apt install libblas-dev liblapack-dev openmpi-bin libopenmpi-dev libscalapack-openmpi-dev

      - name: pip install
        run: |
          python -m pip install -U pip
          python -m pip install numpy scipy toml

      - name: make workspace
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: cmake
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake -DCMAKE_CXX_COMPILER=${{matrix.compiler}} -DCMAKE_VERBOSE_MAKEFILE=ON $GITHUB_WORKSPACE

      - name: build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build ./ -j4

      - name: ctest
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: OMP_NUM_THREADS=1 ctest -V
