name: Test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, macos-10.15]
        compiler: [c++, g++-9, g++-11]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # - name: apt
      #   run: |
      #     sudo apt update
      #     sudo apt install openmpi-bin libopenmpi-dev libscalapack-openmpi-dev

      - name: pip install
        run: |
          python3 -m pip install -U pip
          python3 -m pip install numpy scipy toml

      - name: make workspace
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: cmake
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} $GITHUB_WORKSPACE

      - name: build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build ./ -j4

      - name: ctest
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ctest -V
