name: macOS

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1,15 * *' # JST 9:00 AM, 1st and 15th of every month

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-26, macos-14]
        compiler: [c++, g++-15, g++-13]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.13"

      - name: pip install
        run: |
          python3 -m pip install -U pip
          python3 -m pip install numpy scipy toml pytest

      - name: make workspace
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: cmake
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} -DCMAKE_VERBOSE_MAKEFILE=ON $GITHUB_WORKSPACE

      - name: build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build ./ -j4

      - name: ctest
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: OMP_NUM_THREADS=1 ctest -V
