name: macOS

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11]
        compiler: [g++-10]
        # os: [macos-12, macos-11]
        # compiler: [c++, g++-12]
        # include:
        #   - os: macos-12
        #     compiler: g++-11
        #   - os: macos-11
        #     compiler: g++-10

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: pip install
        run: |
          python3 -m pip install -U pip
          python3 -m pip install numpy scipy toml

      - name: make workspace
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: cmake
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} -DCMAKE_VERBOSE_MAKEFILE=ON $GITHUB_WORKSPACE

      - name: build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build ./ -j4

      - name: ctest
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: OMP_NUM_THREADS=1 ctest -V -R FT_TFI_square
