name: RunTest

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: apt
        run: |
          sudo apt install openmpi-bin libopenmpi-dev libscalapack-openmpi-dev

      - name: pip install
        run: |
          python -m pip install -U pip
          python -m pip install numpy scipy toml

      - name: make workspace
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: cmake
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake $GITHUB_WORKSPACE

      - name: build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build ./

      - name: ctest
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ctest -V
