# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
# Triggers the workflow on push
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: apt
        run: |
          sudo apt install openmpi-bin libopenmpi-dev libscalapack-openmpi-dev

      - name: pip install
        run: |
          python -m pip install -U pip
          python -m pip install numpy scipy toml

      - name: make workspace
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: cmake
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake $GITHUB_WORKSPACE

      - name: build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build ./

      - name: ctest
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ctest -V
